In [5]:
import pandas as pd
import os
import glob
import numpy as np
import re

In [6]:
directory_path = "//"
csv_files = glob.glob(os.path.join(directory_path, "*.csv"))

print(f"Found {len(csv_files)} CSV files.")

Found 5 CSV files.


In [27]:
illuminate = pd.read_csv(
    os.path.join(directory_path, "Data/IlluminateData2025.csv"),
    encoding='cp1252',
    low_memory=True
)

In [8]:
final_df = pd.read_csv(
    os.path.join(directory_path, "Final_DF.csv"),
    low_memory=True
)

/var/folders/h6/zpsbdpxs6dxg5vq66fkdgnr00000gp/T/ipykernel_67410/3383152201.py:1: DtypeWarning: Columns (9,12,20) have mixed types. Specify dtype option on import or set low_memory=False.
  final_df = pd.read_csv(


In [28]:
illuminate.rename(columns={'Mask_StudentPersonkey': 'student_id'}, inplace=True)

In [13]:
for col in illuminate.columns:
    unique_vals = illuminate[col].unique()
    print(f"Column: {col} ({len(unique_vals)} unique values)")
    print(unique_vals[:10])  # Show first 10
    print("-" * 50)

Column: schoolyearnumberspring (1 unique values)
[2025]
--------------------------------------------------
Column: unitnumber (13 unique values)
['3' '2' '4' '1' '9' '8' '5' '6' '7' '5A']
--------------------------------------------------
Column: student_id (75082 unique values)
[406954 405935 728618 728056 728145 581810 612266 575620 397028 389057]
--------------------------------------------------
Column: title (5 unique values)
['language arts' 'math' 'Language Arts' 'social sciences' 'Science']
--------------------------------------------------
Column: AssessmentId (224 unique values)
[379494 356052 379314 357687 383115 341795 392299 356893 338215 376921]
--------------------------------------------------
Column: responsedatevalue (241 unique values)
['2025-01-13 00:00:00' '2024-10-14 00:00:00' '2025-02-14 00:00:00'
 '2024-12-19 00:00:00' '2025-02-11 00:00:00' '2024-09-16 00:00:00'
 '2025-03-26 00:00:00' '2024-09-20 00:00:00' '2024-12-17 00:00:00'
 '2024-11-11 00:00:00']
----------

In [11]:
for col in final_df.columns:
    unique_vals = final_df[col].unique()
    print(f"Column: {col} ({len(unique_vals)} unique values)")
    print(unique_vals[:10])  # Show first 10
    print("-" * 50)

Column: GradeLevel (4 unique values)
[ 9 10 11 12]
--------------------------------------------------
Column: SchoolYearId (3 unique values)
[33 34 35]
--------------------------------------------------
Column: SchoolYear (3 unique values)
['2022-2023' '2023-2024' '2024-2025']
--------------------------------------------------
Column: MarkingPeriodCode (7 unique values)
['S1' 'S2' 'R1' 'X6' 'X4' 'X2' 'Q2']
--------------------------------------------------
Column: MarkingPeriodStartDate (15 unique values)
['2022-08-08 00:00:00.000' '2023-01-04 00:00:00.000'
 '2023-05-31 00:00:00.000' '2023-04-17 00:00:00.000'
 '2022-09-22 00:00:00.000' '2023-08-07 00:00:00.000'
 '2024-01-03 00:00:00.000' '2023-10-09 00:00:00.000'
 '2024-06-05 00:00:00.000' '2024-04-15 00:00:00.000']
--------------------------------------------------
Column: MarkingPeriodEndDate (14 unique values)
['2022-12-16 00:00:00.000' '2023-05-25 00:00:00.000'
 '2023-07-12 00:00:00.000' '2023-02-17 00:00:00.000'
 '2022-11-02 00:00

In [29]:
# Ensure both have consistent column name
final_student_ids = final_df['student_id'].astype(str).unique()
illuminate['student_id'] = illuminate['student_id'].astype(str)

# Filter illuminate based on student_id in final_df
illuminate_filtered = illuminate[illuminate['student_id'].isin(final_student_ids)].copy()

# Map 'title' column to standardized 'DepartmentDesc'
title_map = {
    'language arts': 'LANGUAGE ARTS',
    'Language Arts': 'LANGUAGE ARTS',
    'math': 'MATH',
    'social sciences': 'SOCIAL SCIENCES',
    'Science': 'SCIENCE'
}
illuminate_filtered['DepartmentDesc'] = illuminate_filtered['title'].map(title_map)
illuminate_filtered.drop(columns=['title'], inplace=True)

In [15]:
# title_map = {
#     'language arts': 'LANGUAGE ARTS',
#     'Language Arts': 'LANGUAGE ARTS',
#     'math': 'MATH',
#     'social sciences': 'SOCIAL SCIENCES',
#     'Science': 'SCIENCE'
# }
# illuminate_filtered['Department'] = illuminate_filtered['Department'].map(title_map)

In [30]:
# Drop columns from illuminate_filtered
# illuminate_filtered.drop(columns=[
#     "CurrentSchoolDetailFCSID",
#     "SchoolId",
#     "stdgrouping",
#     "CurrentSchoolName",
#     "standard_id"
# ], inplace=True)

# Export the cleaned DataFrame to CSV
illuminate_filtered.to_csv("cleaned_illuminate.csv", index=False)

In [17]:
for col in illuminate_filtered.columns:
    unique_vals = illuminate_filtered[col].unique()
    print(f"Column: {col} ({len(unique_vals)} unique values)")
    print(unique_vals[:10])  # Show first 10
    print("-" * 50)

Column: schoolyearnumberspring (1 unique values)
[2025]
--------------------------------------------------
Column: unitnumber (13 unique values)
['4' '2' '1' '6' '5' '5A' '3' '4A' '7' '5B']
--------------------------------------------------
Column: student_id (19158 unique values)
['728618' '391268' '368109' '332765' '314909' '765900' '762208' '410786'
 '574835' '445055']
--------------------------------------------------
Column: AssessmentId (72 unique values)
[379314 370501 355450 341204 395513 338346 391222 341203 383428 393610]
--------------------------------------------------
Column: responsedatevalue (214 unique values)
['2025-02-14 00:00:00' '2024-11-18 00:00:00' '2024-10-01 00:00:00'
 '2024-09-16 00:00:00' '2025-04-03 00:00:00' '2024-12-06 00:00:00'
 '2025-04-02 00:00:00' '2025-03-10 00:00:00' '2024-09-12 00:00:00'
 '2024-09-19 00:00:00']
--------------------------------------------------
Column: DateValue (214 unique values)
['2025-02-14 00:00:00' '2024-11-18 00:00:00' '2024-

In [32]:
display(illuminate_filtered[illuminate_filtered['student_id'] == '368109'])

schoolyearnumberspring unitnumber student_id  AssessmentId  \
16                         2025          1     368109        355450   
23326                      2025          4     368109        379314   
59227                      2025          1     368109        356733   
94232                      2025          4     368109        379247   
130417                     2025          6     368109        338350   
...                         ...        ...        ...           ...   
4667050                    2025          1     368109        355450   
4706927                    2025          3     368109        378813   
4801497                    2025          4     368109        379247   
4836828                    2025          1     368109        356733   
4845508                    2025          3     368109        380389   

           responsedatevalue            DateValue  Response_points  \
16       2024-10-01 00:00:00  2024-10-01 00:00:00             17.0   
23326    2025-02-24 00:00:00  2025-02-24 00:00:00             17.0   
59227    2024-09-10 00:00:00  2024-09-10 00:00:00             14.0   
94232    2025-02-27 00:00:00  2025-02-27 00:00:00             15.0   
130417   2025-03-17 00:00:00  2025-03-17 00:00:00              8.0   
...                      ...                  ...              ...   
4667050  2024-10-01 00:00:00  2024-10-01 00:00:00             17.0   
4706927  2025-03-11 00:00:00  2025-03-11 00:00:00              9.0   
4801497  2025-02-27 00:00:00  2025-02-27 00:00:00             15.0   
4836828  2024-09-10 00:00:00  2024-09-10 00:00:00             14.0   
4845508  2024-12-13 00:00:00  2024-12-13 00:00:00             17.0   

         Response_points_possible  Response_percent_correct     Department  \
16                           17.0                    100.00  language arts   
23326                        17.0                    100.00  language arts   
59227                        14.0                    100.00        Science   
94232                        19.0                     78.95        Science   
130417                       15.0                     53.33           math   
...                           ...                       ...            ...   
4667050                      17.0                    100.00  language arts   
4706927                      15.0                     60.00        Science   
4801497                      19.0                     78.95        Science   
4836828                      14.0                    100.00        Science   
4845508                      17.0                    100.00  language arts   

         ...  condition pointsvarchar  \
16       ...  Extension           6/6   
23326    ...  Extension           6/6   
59227    ...  Extension           2/2   
94232    ...    Reteach           2/3   
130417   ...    Reteach           2/3   
...      ...        ...           ...   
4667050  ...  Extension           2/2   
4706927  ...    Reteach           1/3   
4801497  ...    Reteach           2/3   
4836828  ...  Extension           3/3   
4845508  ...  Extension           1/1   

                                            categorytitle  \
16                                           Grades: 9-10   
23326                                        Grades: 9-10   
59227                                             Biology   
94232                                             Biology   
130417   High School – Geometry: Concepts and Connections   
...                                                   ...   
4667050                                      Grades: 9-10   
4706927                                           Biology   
4801497                                           Biology   
4836828                                           Biology   
4845508                                     Grades: 11-12   

                                               stdgrouping SchoolId  \
16       ELAGSE9-10RI2 Determine a central idea of a te...       83   
23326    E

In [33]:
test = pd.read_csv(
    os.path.join(directory_path, "Data/cleaned_illuminate.csv"),
    low_memory=True
)
display(test[test['student_id'] == 368109])

student_id     Department  StandardGradeLevel  \
3           368109  LANGUAGE ARTS                 9.0   
2013        368109  LANGUAGE ARTS                 9.0   
11801       368109  LANGUAGE ARTS                 9.0   
12610       368109  LANGUAGE ARTS                 9.0   
50551       368109  LANGUAGE ARTS                 9.0   
60543       368109  LANGUAGE ARTS                 9.0   
72558       368109  LANGUAGE ARTS                 9.0   
107051      368109  LANGUAGE ARTS                 9.0   
113557      368109  LANGUAGE ARTS                 9.0   
127722      368109  LANGUAGE ARTS                 9.0   
215924      368109  LANGUAGE ARTS                 9.0   
232012      368109  LANGUAGE ARTS                 9.0   
240125      368109  LANGUAGE ARTS                 9.0   
243628      368109  LANGUAGE ARTS                 9.0   
260880      368109  LANGUAGE ARTS                 9.0   
276344      368109  LANGUAGE ARTS                 9.0   
296933      368109  LANGUAGE ARTS                 9.0   
298313      368109  LANGUAGE ARTS                 9.0   
320409      368109  LANGUAGE ARTS                 9.0   
330070      368109  LANGUAGE ARTS                 9.0   
333950      368109  LANGUAGE ARTS                 9.0   
356511      368109  LANGUAGE ARTS                 9.0   
358343      368109  LANGUAGE ARTS                 9.0   
385374      368109  LANGUAGE ARTS                 9.0   
394447      368109  LANGUAGE ARTS                 9.0   
403760      368109  LANGUAGE ARTS                 9.0   
410109      368109  LANGUAGE ARTS                 9.0   
416908      368109  LANGUAGE ARTS                 9.0   
432789      368109  LANGUAGE ARTS                11.0   

        Response_percent_correct responsedatevalue          condition  \
3                         100.00        2024-10-01          Extension   
2013                      100.00        2025-02-24          Extension   
11801                     100.00        2025-02-24          Extension   
12610                     100.00        2024-10-01          Extension   
50551                     100.00        2024-10-01          Extension   
60543                     100.00        2024-12-13          Extension   
72558                     100.00        2024-12-13          Extension   
107051                     94.44        2024-11-13          Extension   
113557                     94.44        2024-11-13  Review & Practice   
127722                    100.00        2025-02-24          Extension   
215924                    100.00        2024-12-13          Extension   
232012                    100.00        2025-02-24          Extension   
240125                    100.00        2024-12-13          Extension   
243628                    100.00        2024-12-13          Extension   
260880                    100.00        2025-02-24          Extension   
276344                    100.00        2024-10-01          Extension   
296933                     94.44        2024-11-13          Extension   
298313                    100.00        2025-02-24          Extension   
320409                    100.00        2024-12-13          Extension   
330070                    100.00        2024-10-01          Extension   
333950                     94.44        2024-11-13          Extension   
356511                     94.44        2024-11-13          Extension   
358343                    100.00        2024-10-01          Extension   
385374                     94.44        2024-11-13          Extension   
394447                     94.44        2024-11-13          Extension   
403760                    100.00        2024-12-13          Extension   
410109                    100.00        2024-10-01          Extension   
416908                    100.00        2024-10-01          Extension   
432789                    100.00        2024-12-13          Extension   

       StandardStateNumber  
3            ELAGSE9-10RI2  
2013         ELAGSE9-10RL2  
11801        ELAGSE